-- Supabase schema for Admin Panel
create table if not exists public.credentials (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  role text not null check (role in ('driver','student')),
  created_at timestamp with time zone default now()
);

create table if not exists public.bus_driver (
  id bigint generated by default as identity primary key,
  bus_plate_number text not null,
  bus_number text not null unique,
  driver_name text not null,
  driver_gender text not null,
  driver_contact text not null,
  driver_email text not null unique,
  created_at timestamp with time zone default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  student_number text not null,
  bus_number text not null,
  student_gender text not null,
  semester text not null,
  bus_pass_validity date not null,
  student_email text not null unique,
  student_contact text not null,
  student_name text not null,
  student_prn text not null unique,
  student_department text not null,
  created_at timestamp with time zone default now()
);

create table if not exists public.student_bus_mapping (
  id bigint generated by default as identity primary key,
  student_email text not null,
  bus_number text not null,
  driver_email text not null,
  created_at timestamp with time zone default now()
);

-- Helpful indexes
create index if not exists idx_students_bus_number on public.students(bus_number);
create index if not exists idx_mapping_bus_number on public.student_bus_mapping(bus_number);
